config/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.conf.urls.static import static
from django.conf import settings

schema_view = get_schema_view(
    openapi.Info(
        title="API Documentation",
        default_version='v1',
        description="Your API description",
        terms_of_service="https://www.example.com/policies/terms/",
        contact=openapi.Contact(email="contact@example.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/drf-auth/', include('rest_framework.urls')),
    path('', include('habit_app.urls', namespace='habit')),
    path('users/', include('users.urls', namespace='users')),
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

habit_app/urls.py
from django.urls import path
from habit_app.apps import HabitAppConfig


from habit_app.views import HabitCreateAPIView, HabitListAPIView, HabitRetrieveAPIView, \
    HabitUpdateAPIView, HabitDestroyAPIView, HabitPublicListAPIView, HabitTemplateView, HabitOptionsListView, \
    HabitOptionsDeleteView, HabitOptionsUpdateView, HabitCreateView

app_name = HabitAppConfig.name

urlpatterns = [
    path('api/habit/create/', HabitCreateAPIView.as_view(), name='post_habit'),
    path('api/habit/', HabitListAPIView.as_view(), name='list_get_habit'),
    path('api/habit/public/', HabitPublicListAPIView.as_view(), name='list_get_habit_public'),
    path('api/habit/<int:pk>/', HabitRetrieveAPIView.as_view(), name='detail_get_habit'),
    path('api/habit/update/<int:pk>/', HabitUpdateAPIView.as_view(), name='put_patch_habit'),
    path('api/habit/delete/<int:pk>/', HabitDestroyAPIView.as_view(), name='delete_habit'),

    path('', HabitTemplateView.as_view(), name='home'),

    path('options/create/', HabitCreateView.as_view(), name='options_create'),
    path('options/', HabitOptionsListView.as_view(), name='options_list'),
    path('options/delete/<int:pk>', HabitOptionsDeleteView.as_view(), name='options_delete'),
    path('options/update/<int:pk>', HabitOptionsUpdateView.as_view(), name='options_update'),
]

users/urls.py
from rest_framework import routers, permissions
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

# from django.urls import path

from users.apps import UsersConfig
from users.views import UsersViewSet, LoginView, LogoutView, RegisterView, UserUpdateView
from django.views.generic import TemplateView
from django.urls import path, include

app_name = UsersConfig.name

router = routers.SimpleRouter()
router.register(r'api/users', UsersViewSet, basename='пользователи')

urlpatterns = [
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('', LogoutView.as_view(), name='logout'),
    path('accounts/register/', RegisterView.as_view(), name='register'),
    path('accounts/profile/', UserUpdateView.as_view(), name='profile'),

] + router.urls

habit_app/models.py
from datetime import timedelta
from django.db import models
from django.contrib.auth import get_user_model

NULLABLE = {'blank': True, 'null': True}


class Habit(models.Model):
    NAME = (
        ('Полезная', 'Полезная'),
        ('Приятная', 'Приятная')
    )

    class Period(models.IntegerChoices):
        DAILY = 1, 'Ежедневно'
        IN_ONE_DAY = 2, 'Каждые два дня'
        EVERY_THREE_DAYS = 3, 'Каждые три дня'
        WEEKLY = 7, 'Еженедельно'

    owner = models.ForeignKey(get_user_model(), verbose_name='Пользователь', related_name='habit',
                              on_delete=models.CASCADE, **NULLABLE)
    name = models.CharField(max_length=100, verbose_name='Тип привычки', choices=NAME, default='Полезная')
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания', **NULLABLE)
    place = models.CharField(max_length=100, verbose_name='Место выполнения', **NULLABLE)
    time_when_execute = models.TimeField(verbose_name='Время когда выполнять',)
    action = models.CharField(max_length=150, verbose_name='Действие',)
    nice_habit = models.BooleanField(default=False, verbose_name='Признак приятной привычки')
    related_habit = models.ForeignKey('self', verbose_name='Связанная привычка', **NULLABLE,
                                      on_delete=models.SET_NULL,)
    periodicity = models.SmallIntegerField(verbose_name='Периодичность', choices=Period.choices,
                                           default=Period.DAILY, **NULLABLE)
    reward = models.CharField(max_length=50, verbose_name='Вознаграждение', **NULLABLE)
    lead_time = models.DurationField(default=timedelta(minutes=2), verbose_name='Время на выполнение',)
    is_public = models.BooleanField(verbose_name='Признак публичности', default=True)

    def __str__(self):
        return f'{self.owner} - {self.name}'

    class Meta:
        verbose_name = 'Привычка'
        verbose_name_plural = 'Привычки'
        get_latest_by = '-time_when_execute'
        ordering = ('time_when_execute',)

    def save(self, *args, **kwargs):
        if self.nice_habit:
            self.related_habit = None
            self.reward = ''
            super().save(*args, **kwargs)
        elif not self.nice_habit:
            if self.related_habit is not None:
                self.reward = ''
            elif self.reward:
                self.related_habit = None
            super().save(*args, **kwargs)

habit_app/forms.py
import captcha as captcha
from captcha.fields import CaptchaField
from django import forms
from habit_app.models import Habit


# class StyleFormMixin:
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         for field_name, field in self.fields.items():
#             # field.help_text = 'Some help text for field'
#             if field_name in ['nice_habit', 'is_public']:
#                 field.widget.attrs['class'] = 'form'
#             # elif field_name in ['time_when_execute']:
#             #     field.widget.attrs['class'] = 'Time'
#             else:
#                 field.widget.attrs['class'] = 'form-control'

class HabitCreateForm(forms.ModelForm):
    # captcha = CaptchaField(label='Введите текст ст картинки')

    class Meta:
        model = Habit
        exclude = ('date', 'owner', 'lead_time', 'related_habit', 'name', 'nice_habit', 'is_public')

    def clean(self):

        cleaned_data = super(HabitCreateForm, self).clean()
        related_habit = self.cleaned_data.get("related_habit")
        reward = self.cleaned_data.get("reward")
        nice_habit = self.cleaned_data.get("nice_habit")
        name = self.cleaned_data.get("name")

        if related_habit and reward:
            raise forms.ValidationError(
                'Для полезной привычки нужно указать связанную привычку или '
                'вознаграждение'
                )

        if name == 'Полезная':
            if not related_habit and not reward:
                raise forms.ValidationError(
                        'Для полезной привычки нужно указать связанную привычку или '
                        'вознаграждение'
                )

        if nice_habit:
            if related_habit:
                raise forms.ValidationError('У приятной привычки не может быть связанной привычки')
            elif reward:
                raise forms.ValidationError('У приятной привычки не может быть вознаграждения')

        if name == 'Полезная':
            if nice_habit:
                raise forms.ValidationError('Ели привычка полезная, то должно отсутствовать указание приятной '
                                            'привычки')
        if name == 'Приятная':
            if not nice_habit:
                raise forms.ValidationError('Ели привычка приятная, то должно присутствовать указание приятной '
                                            'привычки')

        if related_habit:
            if not related_habit.nice_habit:
                raise forms.ValidationError(
                    'В связанные привычки могут попадать только привычки с признаком '
                    'приятной привычки'
                    )

habit_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, UpdateView, DeleteView, ListView, CreateView
from rest_framework.permissions import IsAuthenticated, DjangoModelPermissionsOrAnonReadOnly
from rest_framework.generics import ListAPIView, CreateAPIView, RetrieveAPIView, UpdateAPIView, DestroyAPIView
from django.shortcuts import redirect
from habit_app.forms import HabitCreateForm
from habit_app.models import Habit
from habit_app.paginators import HabitPagination
from habit_app.permissions import IsOwner
from habit_app.serializers import HabitSerializer
from habit_app.services import create_reminder, update_reminder, delete_reminder
from django.urls import reverse_lazy

from habit_app.validators import HabitValidator


class HabitCreateAPIView(CreateAPIView):
    queryset = Habit.objects.all()
    serializer_class = HabitSerializer
    permission_classes = [IsAuthenticated]

    def perform_create(self, serializer):
        new_habit = serializer.save()
        new_habit.owner = self.request.user

        create_reminder(new_habit)
        new_habit.save()

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('users:register')
        else:
            return super().dispatch(request, *args, **kwargs)


class HabitListAPIView(ListAPIView):
    queryset = Habit.objects.all()
    serializer_class = HabitSerializer
    pagination_class = HabitPagination
    permission_classes = [IsAuthenticated, IsOwner]

    def get_queryset(self):
        """ Определяем параметры вывода объектов """

        queryset = Habit.objects.filter(owner=self.request.user)
        return queryset


class HabitPublicListAPIView(ListAPIView):
    """ Вывод списка публичных привычек """

    serializer_class = HabitSerializer
    pagination_class = HabitPagination
    permission_classes = [DjangoModelPermissionsOrAnonReadOnly]

    def get_queryset(self):
        """ Определяем параметры вывода объектов """

        queryset = Habit.objects.filter(is_public=True)
        return queryset


class HabitRetrieveAPIView(RetrieveAPIView):
    queryset = Habit.objects.all()
    serializer_class = HabitSerializer
    permission_classes = [IsAuthenticated, IsOwner]


class HabitUpdateAPIView(UpdateAPIView):
    queryset = Habit.objects.all()
    serializer_class = HabitSerializer
    permission_classes = [IsAuthenticated, IsOwner]


    def perform_update(self, serializer):
        habit = serializer.save()
        update_reminder(habit)
        habit.save()


class HabitDestroyAPIView(DestroyAPIView):
    queryset = Habit.objects.all()
    permission_classes = [IsAuthenticated, IsOwner]

    def perform_destroy(self, instance):
        delete_reminder(instance)
        instance.delete()


class HabitTemplateView(TemplateView):
    template_name = 'habit_app/home.html'
    extra_context = {
            'title': "Главная страница",
    }


class HabitCreateView(LoginRequiredMixin, CreateView):
    model = Habit
    form_class = HabitCreateForm
    permission_classes = [IsAuthenticated]
    success_url = reverse_lazy('habit_app:options_list')
    extra_context = {
            'title': "Создать привычку",
    }

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('users:register')
            # return redirect('habit_app:home')
        else:
            return super().dispatch(request, *args, **kwargs)

    # def form_valid(self, form):
    #     self.object = form.save()
    #     self.object.owner = self.request.user
    #     self.object.save()

    def form_valid(self, form):
        self.object = form.save()
        send_params = form.save()
        self.object.owner = self.request.user

        send_params.save()
        self.object.save()
        create_reminder(send_params)
        return super().form_valid(form)


class HabitOptionsListView(ListView):
    model = Habit
    permission_classes = [IsAuthenticated, IsOwner]
    extra_context = {
            'title': "Все привычки",
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(owner=self.request.user)
        return queryset

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('users:register')
        else:
            return super().dispatch(request, *args, **kwargs)


class HabitOptionsDeleteView(LoginRequiredMixin, DeleteView):
    model = Habit
    success_url = reverse_lazy('habit_app:options_list')
    permission_classes = [IsAuthenticated, IsOwner]


class HabitOptionsUpdateView(LoginRequiredMixin, UpdateView):
    model = Habit
    form_class = HabitCreateForm
    # validators = HabitValidator
    permission_classes = [IsAuthenticated, IsOwner]
    success_url = reverse_lazy('habit_app:options_list')
    extra_context = {
            'title': "Редактирование привычки",
    }

    def form_valid(self, form):
        self.object = form.save()
        send_params = form.save()
        self.object.owner = self.request.user

        send_params.save()
        self.object.save()
        return super().form_valid(form)

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(id=self.kwargs.get('pk'))
        return queryset

habit_app/templates/habit_app/includes/inc_footer.html
{% load static %}
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Трекер полезных привычек
                <small class="d-block mb-3 text-muted">&copy; 2024</small>
            </div>
            <div class="col-6 col-sm-auto">
                <h5 class="text-end">Категории</h5>
                <ul class="list-unstyled text-end">
                    <li><a class="text-muted" href="https://t.me/Alexandr_habit_bot">Телеграм бот</a></li>
                    <li><a class="text-muted"
                           href="https://trends.rbc.ru/trends/social/62ebf92d9a7947dc0a62e727">Как привычки помогают
                        жить и зачем создавать новые
                    </a>
                    </li>
                    <li><a class="text-muted" href="https://trends.rbc.ru/trends/social/636e40469a79470a18d08ed1">
                        Что такое трекер привычек и как с помощью него тренировать силу воли</a>
                    </li>
{#                    <li><a class="text-muted" href="http://127.0.0.1:8000/redoc/">#}
{#                        Документация REST API</a>#}
{#                    </li>#}
                </ul>
            </div>
        </div>
    </footer>
{#</div>#}

habit_app/templates/habit_app/includes/inc_navbar.html
{% load static %}

{#<div class=" flex-column p-1 px-md-6">#}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-xxl">
            <a class="navbar-brand">
                <img alt="" width="90" height="50" src=
                        "{% static "images/Logotip3ispr640prod.ico" %}">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'habit_app:home' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#7777ff"
                                 class="bi bi-house-door" viewBox="0 0 16 16">
                                <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293zM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4z"></path>
                            </svg>
                            Главная
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#"
                           role="button" aria-haspopup="true">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#7777ff"
                                 class="bi bi-hand-index" viewBox="0 0 16 16">
                                <path d="M6.75 1a.75.75 0 0 1 .75.75V8a.5.5 0 0 0 1 0V5.467l.086-.004c.317-.012.637-.008.816.027.134.027.294.096.448.182.077.042.15.147.15.314V8a.5.5 0 1 0 1 0V6.435l.106-.01c.316-.024.584-.01.708.04.118.046.3.207.486.43.081.096.15.19.2.259V8.5a.5.5 0 0 0 1 0v-1h.342a1 1 0 0 1 .995 1.1l-.271 2.715a2.5 2.5 0 0 1-.317.991l-1.395 2.442a.5.5 0 0 1-.434.252H6.035a.5.5 0 0 1-.416-.223l-1.433-2.15a1.5 1.5 0 0 1-.243-.666l-.345-3.105a.5.5 0 0 1 .399-.546L5 8.11V9a.5.5 0 0 0 1 0V1.75A.75.75 0 0 1 6.75 1M8.5 4.466V1.75a1.75 1.75 0 1 0-3.5 0v5.34l-1.2.24a1.5 1.5 0 0 0-1.196 1.636l.345 3.106a2.5 2.5 0 0 0 .405 1.11l1.433 2.15A1.5 1.5 0 0 0 6.035 16h6.385a1.5 1.5 0 0 0 1.302-.756l1.395-2.441a3.5 3.5 0 0 0 .444-1.389l.271-2.715a2 2 0 0 0-1.99-2.199h-.581a5 5 0 0 0-.195-.248c-.191-.229-.51-.568-.88-.716-.364-.146-.846-.132-1.158-.108l-.132.012a1.26 1.26 0 0 0-.56-.642 2.6 2.6 0 0 0-.738-.288c-.31-.062-.739-.058-1.05-.046zm2.094 2.025"></path>
                            </svg>
                            Возможности
                        </a>
                        {#                    <li class="nav-item dropdown">#}
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'habit_app:options_create' %}">Создать
                                привычку</a>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'habit_app:options_list' %}">
                                Все ваши привычки</a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <div class="d-grid gap-2 d-md-flex justify-content-end">
                    {% if user.is_authenticated %}
                        <svg width="35" height="35" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg">
                            <path fill="#70bf2b"
                                  d="M1412 734q0-28-18-46l-91-90q-19-19-45-19t-45 19l-408 407-226-226q-19-19-45-19t-45 19l-91 90q-18 18-18 46 0 27 18 45l362 362q19 19 45 19 27 0 46-19l543-543q18-18 18-45zm252 162q0 209-103 385.5t-279.5 279.5-385.5 103-385.5-103-279.5-279.5-103-385.5 103-385.5 279.5-279.5 385.5-103 385.5 103 279.5 279.5 103 385.5z"></path>
                        </svg>
                        <a href="{% url "users:profile" %}" class="btn btn-outline-light btn-md mx-2 elem">

                            {{ user.first_name }} {{ user.last_name }}
                        </a>
                        <form method="post" action="{% url "users:logout" %}">
                            {% csrf_token %}
                            <button class="btn btn-outline-light btn-md elem" type="submit">Выход

                            </button>
                        </form>
                    {% else %}
                        <p href="#" class="anon text-center">
                            Анонимный пользователь
                        </p>
                        <a href="{% url "users:login" %}" class="btn
                                            btn-outline-light btn-md mx-2 elem"
                        >Вход</a>
                        <a href="{% url "users:register" %}" class="btn btn-outline-light btn-md elem"
                        >Регистрация</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>